# Generated by Django 2.2.2 on 2019-08-13 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('uploaded_pdf', models.FileField(blank=True, null=True, upload_to='uploaded_pdf/%Y/%m/%d/', verbose_name='Исходный документ(pdf)')),
                ('customer_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата документа')),
                ('doc_type', models.CharField(default=1, max_length=64, verbose_name='Тип документа')),
                ('type_object', models.CharField(default=1, max_length=64, verbose_name='вид объекта учета')),
                ('name_object', models.CharField(default=1, max_length=64, verbose_name='наименование объекта учета')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
                ('width_image_schema', models.IntegerField(blank=True, default=50, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Размер схемы %')),
                ('engineer_name', models.CharField(default='Клименко М.В.', max_length=64, null=True, verbose_name='имя инженера')),
                ('customer_name', models.CharField(default='Панин В.Э.', max_length=64, null=True, verbose_name='имя начальника отделения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='схема помещения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='Ордер')),
            ],
            options={
                'verbose_name': 'схема помещения',
                'verbose_name_plural': 'схемы помещений',
            },
        ),
        migrations.CreateModel(
            name='ExplicationSquareTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_total_summa_global', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Общая площадь ( с летними ):')),
                ('square_total_summa', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь общая, кв.м. -Всего- Итого:')),
                ('square_general_summa', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь основная (жилая), кв.м. Итого:')),
                ('square_advanced_summa', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь вспом., кв.м. Итого:')),
                ('square_logdi_summa', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь лоджий, кв.м. Итого:')),
                ('square_balkon_summa', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь балконов, кв.м. Итого:')),
                ('square_another_summa', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь прочих, кв.м. Итого:')),
                ('order', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order')),
            ],
            options={
                'verbose_name': 'Общая площадь помещений',
                'verbose_name_plural': 'Общие площади помещений',
            },
        ),
        migrations.CreateModel(
            name='ExplicationListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appart_number_item', models.CharField(blank=True, max_length=3, verbose_name='№№ комнат')),
                ('appart_name_item', models.CharField(blank=True, max_length=64, null=True, verbose_name='Характеристики комнат и помещений')),
                ('square_total_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь общая, кв.м. -Всего-')),
                ('square_general_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь основная (жилая), кв.м.')),
                ('square_advanced_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь вспом., кв.м.')),
                ('square_logdi_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь лоджий, кв.м')),
                ('square_balkon_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь балконов, кв.м.')),
                ('square_another_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь прочих, кв.м.')),
                ('floor_number', models.CharField(blank=True, max_length=64, verbose_name='Этаж')),
                ('height_item', models.CharField(blank=True, max_length=5, null=True, verbose_name='Высота помешения')),
                ('apart_number', models.CharField(blank=True, max_length=64, verbose_name='Номер помещения (квартиры)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_list', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='g')),
            ],
            options={
                'verbose_name': 'ряд таблицы экспликации',
                'verbose_name_plural': 'Таблица экспликации',
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_rf', models.CharField(blank=True, max_length=64, null=True, verbose_name='субъект РФ')),
                ('rayon', models.CharField(blank=True, max_length=64, null=True, verbose_name='Район')),
                ('mun_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Муниципальное образование тип')),
                ('mun_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Муниципальное образование наименование ')),
                ('city_type', models.CharField(choices=[('город', 'город'), ('деревня', 'деревня'), ('село', 'село'), ('поселок', 'поселок')], default=1, max_length=64, verbose_name='Населенный пункт тип')),
                ('city_name', models.CharField(blank=True, max_length=64, verbose_name='Населенный пункт наименование')),
                ('street_type', models.CharField(choices=[('улица', 'улица'), ('переулок', 'переулок'), ('проспект', 'проспект'), ('проезд', 'проезд'), ('шоссе', 'шоссе'), ('площадь', 'площадь')], default=1, max_length=64, verbose_name='Улица (проспект, переулок и т. д.)')),
                ('street', models.CharField(blank=True, max_length=64, null=True, verbose_name='название улицы (проспекта, переулка и т. д.)')),
                ('house_number', models.CharField(blank=True, max_length=64, verbose_name='Номер дома')),
                ('corpus_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер корпуса')),
                ('litera', models.CharField(blank=True, max_length=64, null=True, verbose_name='Литера')),
                ('build_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер строения')),
                ('another_places', models.CharField(blank=True, max_length=64, null=True, verbose_name='Иное описание местоположения')),
                ('order', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='статус заказа')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреc',
            },
        ),
    ]
