# Generated by Django 2.2.2 on 2019-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64, null=True, verbose_name='имя инженера')),
                ('customer_adress', models.TextField(null=True, verbose_name='адрес помещения')),
                ('customer_data', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активен?')),
                ('image', models.ImageField(upload_to='schema_images/', verbose_name='схема помещения')),
                ('image_2', models.ImageField(upload_to='explications_images/', verbose_name='таблица экспликации')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
