# Generated by Django 2.2.2 on 2019-08-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='fullpdf_url_staff',
        ),
    ]
