# Generated by Django 2.2.2 on 2019-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_pdf/%Y/%m/%d/', verbose_name='Исходный документ(pdf)'),
        ),
    ]
