# Generated by Django 2.2.2 on 2019-08-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecAppartListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_appart_text', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хар-ка помешения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'хар-ка помещений',
                'verbose_name_plural': 'Хар-ки помещений',
            },
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='appart_name_item',
            field=models.CharField(blank=True, choices=[('ТПЖП', 'ТПЖП'), ('Экспликация на помещение', 'Экспликация на помещение')], default=1, max_length=64, null=True, verbose_name='Характеристики комнат и помещений'),
        ),
    ]
