# Generated by Django 2.2.2 on 2019-06-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0002_order_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
