# Generated by Django 2.2.2 on 2019-08-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0002_order_uploaded_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='height_item',
        ),
        migrations.AddField(
            model_name='explicationlistitem',
            name='floor_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='explicationlistitem',
            name='height_item',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота помешения'),
        ),
    ]
