# Generated by Django 2.2.2 on 2019-08-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0002_remove_orderimage_fullpdf_url_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='fullpdf_url_staff',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Полный итоговый документ'),
        ),
    ]
