# Generated by Django 2.2.2 on 2019-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0002_remove_order_new_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_source',
            field=models.BooleanField(default=True, verbose_name='если исходник старого образца, то снимите галку'),
        ),
    ]
