# Generated by Django 2.2.2 on 2019-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0002_auto_20190805_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specappartlistitem',
            options={'verbose_name': 'хар-ка помещений', 'verbose_name_plural': 'xар-ки помещений'},
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='appart_name_item',
            field=models.CharField(blank=True, choices=[('жилая изолированная', 'жилая изолированная'), ('уборная', 'уборная'), ('кухня', 'кухня'), ('лоджия', 'лоджия')], default=1, max_length=64, null=True, verbose_name='Характеристики комнат и помещений'),
        ),
        migrations.AlterField(
            model_name='specappartlistitem',
            name='spec_appart_text',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хар-ка помещения'),
        ),
    ]
