# Generated by Django 2.2.2 on 2019-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0002_auto_20190813_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='another_places',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Иное описание местоположения'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='build_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер строения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='corpus_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер корпуса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='litera',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Литера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='mun_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Муниципальное образование наименование '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='mun_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Муниципальное образование тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='rayon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Район'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='название улицы (проспекта, переулка и т. д.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='subject_rf',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='субъект РФ'),
            preserve_default=False,
        ),
    ]
