# Generated by Django 2.2.2 on 2019-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0003_orderimage_fullpdf_url_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='fullpdf_url_staff',
            field=models.URLField(blank=True, max_length=250, verbose_name='Полный итоговый документ'),
        ),
    ]
