# Generated by Django 2.2.2 on 2019-08-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0003_auto_20190814_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='build_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер строения'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city_name',
            field=models.CharField(blank=True, default='Москва', max_length=64, verbose_name='Населенный пункт наименование'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='corpus_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер корпуса'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='litera',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='mun_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Муниципальное образование наименование '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='mun_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Муниципальное образование тип'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='rayon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='название улицы (проспекта, переулка и т. д.)'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='subject_rf',
            field=models.CharField(blank=True, default='Москва', max_length=64, verbose_name='субъект РФ'),
        ),
    ]
