# Generated by Django 2.2.2 on 2019-08-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0003_auto_20190811_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicationlistitem',
            name='height_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Высота помешения'),
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='square_advanced_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь вспом., кв.м.'),
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='square_another_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь прочих, кв.м.'),
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='square_balkon_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь балконов, кв.м.'),
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='square_general_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь основная (жилая), кв.м.'),
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='square_logdi_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь лоджий, кв.м'),
        ),
        migrations.AlterField(
            model_name='explicationlistitem',
            name='square_total_item',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Площадь общая, кв.м. -Всего-'),
        ),
    ]
