# Generated by Django 2.2.2 on 2019-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0003_auto_20190805_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicationlistitem',
            name='appart_name_item',
            field=models.CharField(blank=True, choices=[('жилая изолированная', 'жилая изолированная'), ('уборная', 'уборная'), ('кухня', 'кухня'), ('лоджия', 'лоджия'), ('гостиная', 'гостиная')], default=1, max_length=64, null=True, verbose_name='Характеристики комнат и помещений'),
        ),
    ]
