# Generated by Django 2.2.2 on 2020-01-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0004_auto_20200126_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='city_name_general',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='city_type_general',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='micro_rayon',
        ),
    ]
