# Generated by Django 2.2.2 on 2019-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0004_auto_20190811_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='another_places',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Иное описание местоположения'),
        ),
    ]
