# Generated by Django 2.2.2 on 2019-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0004_auto_20190816_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='micro_rayon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='микрорайон'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city_type',
            field=models.CharField(choices=[('город', 'город'), ('деревня', 'деревня'), ('село', 'село'), ('поселок', 'поселок'), ('поселение', 'поселение')], default=1, max_length=64, verbose_name='Населенный пункт тип'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='fullpdf_url_staff',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
