# Generated by Django 2.2.2 on 2019-06-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0004_order_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
