# Generated by Django 2.2.2 on 2019-07-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0005_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='object_list',
            field=models.CharField(max_length=64, null=True, verbose_name='cписок объектов'),
        ),
    ]
