# Generated by Django 2.2.2 on 2020-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0005_auto_20200127_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city_name',
            field=models.CharField(blank=True, default='Москва', max_length=64, verbose_name='Населенный пункт наименование'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city_type',
            field=models.CharField(default='город', max_length=64, verbose_name='Населенный пункт тип'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='subject_rf',
            field=models.CharField(choices=[('MOCKBA', 'город Москва'), ('MO', 'Москоская область')], default='МОСКВА', max_length=64, verbose_name='субъект РФ'),
        ),
    ]
