# Generated by Django 2.2.2 on 2019-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0005_auto_20190811_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='floor_number_adress',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этаж'),
        ),
    ]
