# Generated by Django 2.2.2 on 2019-08-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0005_auto_20190816_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='micro_rayon',
        ),
    ]
