# Generated by Django 2.2.2 on 2020-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0006_auto_20200128_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='street_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Улица (проспект, переулок и т. д.)'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='subject_rf',
            field=models.CharField(blank=True, default='Москва', max_length=64, verbose_name='субъект РФ'),
        ),
    ]
