# Generated by Django 2.2.2 on 2019-08-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0006_remove_adress_micro_rayon'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='micro_rayon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='микрорайон'),
        ),
    ]
