# Generated by Django 2.2.2 on 2019-07-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0007_auto_20190702_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='order',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='статус заказа'),
        ),
    ]
