# Generated by Django 2.2.2 on 2019-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0007_adress_micro_rayon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city_type',
            field=models.CharField(default='', max_length=64, verbose_name='Населенный пункт тип'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street_type',
            field=models.CharField(default='', max_length=64, verbose_name='Улица (проспект, переулок и т. д.)'),
        ),
    ]
