# Generated by Django 2.2.2 on 2019-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0008_auto_20190811_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='explicationsquaretotal',
            name='square_total_summa_global',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Общая площадь ( с летними ):'),
        ),
    ]
