# Generated by Django 2.2.2 on 2019-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0009_auto_20190702_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='apart_number',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер помещения (квартиры)'),
        ),
        migrations.AddField(
            model_name='adress',
            name='flow_number',
            field=models.CharField(max_length=64, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='corpus_number',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер корпуса'),
        ),
    ]
