# Generated by Django 2.2.2 on 2020-01-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0011_auto_20200128_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='subject_rf',
        ),
        migrations.AddField(
            model_name='order',
            name='subj_type',
            field=models.CharField(default='null', max_length=64, verbose_name='субъект РФ'),
        ),
    ]
