# Generated by Django 2.2.2 on 2019-07-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0012_auto_20190702_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='litera',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер корпуса'),
        ),
    ]
