# Generated by Django 2.2.2 on 2020-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0013_auto_20200128_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('Экспликация на помещение', 'Экспликация на помещение'), ('ТПЖП', 'ТПЖП'), ('тест', 'тест')], default='Экспликация на помещение', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subj_type',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Московская область', 'Московская область')], default='Москва', max_length=64, verbose_name='субъект РФ'),
        ),
    ]
