# Generated by Django 2.2.2 on 2019-07-05 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0013_adress_litera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреc'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='another_places',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='Иное описание местоположения'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='apart_number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=64, verbose_name='Номер помещения (квартиры)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='build_number',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Номер строения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='city_name',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Населенный пункт наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='city_type',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Населенный пункт тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='corpus_number',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Номер корпуса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='flow_number',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_number',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='litera',
            field=models.CharField(blank=True, max_length=64, verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='mun_name',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Муниципальное образование наименование '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='mun_type',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Муниципальное образование тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='rayon',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Район'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='название улицы (проспекта, переулка и т. д.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='street_type',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='Улица (проспект, переулок и т. д.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='subject_rf',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='субъект РФ'),
            preserve_default=False,
        ),
    ]
