# Generated by Django 2.2.2 on 2020-01-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0014_auto_20200128_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='full_adress',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='полный адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('Экспликация на помещение', 'Экспликация на помещение'), ('ТПЖП', 'ТПЖП')], default='Экспликация на помещение', max_length=64, verbose_name='Тип документа'),
        ),
    ]
