# Generated by Django 2.2.2 on 2019-07-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0015_auto_20190706_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='object_list',
        ),
        migrations.AddField(
            model_name='adress',
            name='height_item',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота помешения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ExplicationListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appart_number_item', models.CharField(blank=True, max_length=3, verbose_name='№№ комнат')),
                ('appart_name_item', models.CharField(blank=True, max_length=64, verbose_name='Характеристики комнат и помещений')),
                ('square_total_item', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь общая, кв.м. -Всего-')),
                ('square_general_item', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь основная (жилая), кв.м.')),
                ('square_advanced_item', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь вспом., кв.м.')),
                ('square_logdi_item', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь лоджий, кв.м')),
                ('square_balkon_item', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь балконов, кв.м.')),
                ('square_another_item', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь прочих, кв.м.')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_list', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='g')),
            ],
            options={
                'verbose_name': 'Строка таблицы экспликации',
                'verbose_name_plural': 'Строка таблицы экспликации',
            },
        ),
    ]
