# Generated by Django 2.2.2 on 2020-01-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0016_auto_20200128_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tech_pasp_pdf', models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Тех.паспорт')),
                ('tech_pasp_pdf_url', models.URLField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_tech_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdftrans.Order', verbose_name='Тех.паспорт ордера')),
            ],
            options={
                'verbose_name': 'Тех.паспорт',
                'verbose_name_plural': 'Тех.паспорта',
            },
        ),
    ]
