# Generated by Django 2.2.2 on 2020-01-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0018_auto_20200130_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_object',
            field=models.CharField(choices=[('Помещение', 'Помещение')], default='Помещение', max_length=64, verbose_name='вид объекта учета'),
        ),
    ]
