# Generated by Django 2.2.2 on 2020-01-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0019_auto_20200130_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(default='', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_object',
            field=models.CharField(default='', max_length=64, verbose_name='наименование объекта учета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subj_type',
            field=models.CharField(default='', max_length=64, verbose_name='субъект РФ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_object',
            field=models.CharField(default='', max_length=64, verbose_name='вид объекта учета'),
        ),
    ]
