# Generated by Django 2.2.2 on 2020-01-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0020_auto_20200130_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('Экспликация на помещение', 'Экспликация на помещение'), ('Технический паспорт', 'Технический паспорт')], default='Экспликация на помещение', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_object',
            field=models.CharField(choices=[('квартира', 'квартира')], default='квартира', max_length=64, verbose_name='наименование объекта учета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subj_type',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Московская область', 'Московская область')], default='Москва', max_length=64, verbose_name='субъект РФ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_object',
            field=models.CharField(choices=[('Помещение', 'Помещение')], default='Помещение', max_length=64, verbose_name='вид объекта учета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_pdf',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='uploaded_pdf/', verbose_name='Исходный документ(pdf)'),
        ),
        migrations.CreateModel(
            name='OrderTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tech_pasp_pdf', models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Тех.паспорт')),
                ('tech_pasp_pdf_url', models.URLField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_tech_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdftrans.Order', verbose_name='Тех.паспорт ордера')),
            ],
            options={
                'verbose_name': 'Тех.паспорт',
                'verbose_name_plural': 'Тех.паспорта',
            },
        ),
    ]
