# Generated by Django 2.2.2 on 2019-07-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0021_remove_explicationlistitem_square_advanced_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='appart_name_item',
        ),
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='appart_number_item',
        ),
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='square_another_item',
        ),
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='square_balkon_item',
        ),
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='square_general_item',
        ),
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='square_logdi_item',
        ),
        migrations.RemoveField(
            model_name='explicationlistitem',
            name='square_total_item',
        ),
    ]
