# Generated by Django 2.2.2 on 2020-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0022_auto_20200130_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Населенный пункт наименование'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city_type',
            field=models.CharField(default='', max_length=64, verbose_name='Населенный пункт тип'),
        ),
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('Экспликация на помещение', 'Экспликация на помещение'), ('Технический паспорт', 'Технический паспорт')], default='Экспликация на помещение', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_object',
            field=models.CharField(choices=[('квартира', 'квартира'), ('дом', 'дом')], default='квартира', max_length=64, verbose_name='наименование объекта учета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subj_type',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Московская область', 'Московская область')], default='Москва', max_length=64, verbose_name='субъект РФ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_object',
            field=models.CharField(choices=[('Помещение', 'Помещение'), ('здание', 'здание'), ('Склад', 'Склад')], default='Помещение', max_length=64, verbose_name='вид объекта учета'),
        ),
    ]
