# Generated by Django 2.2.2 on 2019-07-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0023_auto_20190726_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExplicationListItem',
        ),
    ]
