# Generated by Django 2.2.2 on 2020-02-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0023_auto_20200202_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_source',
        ),
        migrations.AddField(
            model_name='order',
            name='old_source',
            field=models.BooleanField(default=False, verbose_name='если исходник старого образца, то поставьте галку'),
        ),
    ]
