# Generated by Django 2.2.2 on 2020-02-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0024_auto_20200203_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='old_source',
        ),
    ]
