# Generated by Django 2.2.2 on 2019-07-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0024_delete_explicationlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplicationListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appart_number_item', models.CharField(blank=True, max_length=3, verbose_name='№№ комнат')),
                ('appart_name_item', models.CharField(blank=True, max_length=64, verbose_name='Характеристики комнат и помещений')),
                ('square_total_item', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Площадь общая, кв.м. -Всего-')),
                ('square_general_item', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Площадь основная (жилая), кв.м.')),
                ('square_advanced_item', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Площадь вспом., кв.м.')),
                ('square_logdi_item', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Площадь лоджий, кв.м')),
                ('square_balkon_item', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Площадь балконов, кв.м.')),
                ('square_another_item', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Площадь прочих, кв.м.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_list', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='g')),
            ],
            options={
                'verbose_name': 'ряд таблицы экспликации',
                'verbose_name_plural': 'Таблица экспликации',
            },
        ),
    ]
