# Generated by Django 2.2.2 on 2020-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0025_remove_order_old_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderimage',
            options={'verbose_name': 'схема помещения на этаже', 'verbose_name_plural': 'схемы помещений'},
        ),
        migrations.AddField(
            model_name='orderimage',
            name='floor_for_image',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='план этажа'),
        ),
    ]
