# Generated by Django 2.2.2 on 2020-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0027_auto_20200203_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('Экспликация на помещение', 'Экспликация на помещение'), ('Технический паспорт', 'Технический паспорт')], default='Экспликация на помещение', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_object',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Нежилое', 'Нежилое'), ('Здание', 'Здание'), ('Машиноместо', 'Машиноместо'), ('Гараж', 'Гараж')], default='Квартира', max_length=64, verbose_name='наименование объекта учета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subj_type',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Московская область', 'Московская область')], default='Москва', max_length=64, verbose_name='субъект РФ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_object',
            field=models.CharField(choices=[('Помещение', 'Помещение'), ('Склад', 'Склад')], default='Помещение', max_length=64, verbose_name='вид объекта учета'),
        ),
    ]
