# Generated by Django 2.2.2 on 2020-02-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0028_auto_20200203_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='string_appartment',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Строка с номером помещения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_object',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Помещение', 'Помещение'), ('Здание', 'Здание'), ('Машиноместо', 'Машиноместо'), ('Гараж', 'Гараж')], default='Квартира', max_length=64, verbose_name='наименование объекта учета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_object',
            field=models.CharField(choices=[('Жилое', 'Жилое'), ('Нежилое', 'Нежилое')], default='Жилое', max_length=64, verbose_name='вид объекта учета'),
        ),
    ]
