# Generated by Django 2.2.2 on 2020-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0029_auto_20200217_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='global_appartment_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='тип помещения'),
        ),
        migrations.AddField(
            model_name='adress',
            name='sub_appartment',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='номер подпомещения'),
        ),
        migrations.AddField(
            model_name='adress',
            name='sub_appartment_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='тип подпомещения'),
        ),
    ]
