# Generated by Django 2.2.2 on 2019-07-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0030_auto_20190726_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplicationSquareTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_total_summa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь общая, кв.м. -Всего- SUMMA')),
                ('square_general_summa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь основная (жилая), кв.м. SUMMA')),
                ('square_advanced_summa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь вспом., кв.м. SUMMA')),
                ('square_logdi_summa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь лоджий, кв.м. SUMMA')),
                ('square_balkon_summa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь балконов, кв.м. SUMMA')),
                ('square_another_summa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь прочих, кв.м. SUMMA')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='g')),
            ],
        ),
    ]
