# Generated by Django 2.2.2 on 2020-02-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0030_auto_20200219_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='string_appartment',
        ),
    ]
