# Generated by Django 2.2.2 on 2020-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0031_remove_adress_string_appartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_object',
        ),
        migrations.AlterField(
            model_name='adress',
            name='sub_appartment',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='номер подпомещения'),
        ),
    ]
