# Generated by Django 2.2.2 on 2019-07-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0031_explicationsquaretotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='order',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdftrans.Order', verbose_name='g'),
        ),
    ]
