# Generated by Django 2.2.2 on 2020-02-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0032_auto_20200219_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kadastr_number',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='кадастровый номер комнат'),
        ),
    ]
