# Generated by Django 2.2.2 on 2019-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0033_auto_20190726_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city_type',
            field=models.CharField(choices=[('1', 'город'), ('2', 'деревня'), ('3', 'село'), ('4', 'поселок')], default=1, max_length=64, verbose_name='Населенный пункт тип'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street_type',
            field=models.CharField(choices=[('1', 'улица'), ('2', 'переулок'), ('3', 'проспект'), ('4', 'проезд'), ('5', 'шоссе'), ('6', 'площадь')], default=1, max_length=64, verbose_name='Улица (проспект, переулок и т. д.)'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_advanced_summa',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь вспом., кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_another_summa',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь прочих, кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_balkon_summa',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь балконов, кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_general_summa',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь основная (жилая), кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_logdi_summa',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь лоджий, кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_total_summa',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Площадь общая, кв.м. -Всего- Итого:'),
        ),
    ]
