# Generated by Django 2.2.2 on 2020-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0033_order_kadastr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='qtyroom',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='rayon',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('План и экспликация', 'План и экспликация'), ('Технический паспорт', 'Технический паспорт')], default='План и экспликация', max_length=64, verbose_name='Тип документа'),
        ),
    ]
