# Generated by Django 2.2.2 on 2020-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0034_auto_20200224_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='fullpdf_url_staff',
        ),
        migrations.AlterField(
            model_name='adress',
            name='qtyroom',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='кол-во комнат для МО'),
        ),
    ]
