# Generated by Django 2.2.2 on 2019-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0034_auto_20190727_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_advanced_summa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь вспом., кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_another_summa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь прочих, кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_balkon_summa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь балконов, кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_general_summa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь основная (жилая), кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_logdi_summa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь лоджий, кв.м. Итого:'),
        ),
        migrations.AlterField(
            model_name='explicationsquaretotal',
            name='square_total_summa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь общая, кв.м. -Всего- Итого:'),
        ),
    ]
