# Generated by Django 2.2.2 on 2020-06-04 21:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0035_auto_20200224_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderExplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_header', tinymce.models.HTMLField(verbose_name='текст шапки')),
                ('protocol_type', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdftrans.Order', verbose_name='Ордер')),
            ],
        ),
    ]
