# Generated by Django 2.2.2 on 2020-06-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0036_headerexplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerexplication',
            name='name_template',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя шаблона шапки'),
        ),
    ]
