# Generated by Django 2.2.2 on 2019-07-27 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0037_auto_20190727_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_2',
        ),
        migrations.AddField(
            model_name='order',
            name='width_image_schema',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
