# Generated by Django 2.2.2 on 2020-06-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0037_headerexplication_name_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerexplication',
            options={'verbose_name': 'шаблон шапки', 'verbose_name_plural': 'шаблоны шапки'},
        ),
        migrations.RemoveField(
            model_name='headerexplication',
            name='protocol_type',
        ),
    ]
