# Generated by Django 2.2.2 on 2020-06-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0038_auto_20200605_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderExplication',
        ),
    ]
