# Generated by Django 2.2.2 on 2020-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0039_delete_headerexplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='header_object',
            field=models.CharField(choices=[('default template for header', 'default template for header')], default='HeaderExplication object (1)', max_length=64, verbose_name='тип шапки'),
        ),
    ]
