# Generated by Django 2.2.2 on 2020-06-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0049_cashitog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashitog',
            name='cash_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
