# Generated by Django 2.2.2 on 2020-06-05 22:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0050_auto_20200605_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashitog',
            name='cash_url',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
