# Generated by Django 2.2.2 on 2020-06-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftrans', '0051_auto_20200606_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashitog',
            name='cash_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
