# Generated by Django 2.2.2 on 2019-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='тип документа')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документа',
            },
        ),
        migrations.CreateModel(
            name='NameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='наименование объекта учета')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'наименование объекта учета',
                'verbose_name_plural': 'наименования объекта учета',
            },
        ),
        migrations.CreateModel(
            name='TypeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='вид объекта учета')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'вид объекта учета',
                'verbose_name_plural': 'виды объекта учета',
            },
        ),
    ]
