# Generated by Django 2.2.2 on 2020-01-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_pdftrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='субъект РФ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'субъект РФ',
                'verbose_name_plural': 'субъекты РФ',
            },
        ),
    ]
