# Generated by Django 2.2.2 on 2019-08-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_pdftrans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameobject',
            old_name='object_name',
            new_name='objects_name',
        ),
        migrations.RenameField(
            model_name='typeobject',
            old_name='object_type',
            new_name='objects_type',
        ),
    ]
