# Generated by Django 2.2.2 on 2020-06-04 22:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_pdftrans', '0002_subjecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderExplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_template', models.CharField(blank=True, max_length=128, verbose_name='Имя шаблона шапки')),
                ('text_header', tinymce.models.HTMLField(verbose_name='текст шапки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'шаблон шапки',
                'verbose_name_plural': 'шаблоны шапки',
            },
        ),
    ]
